runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  login: admin

includes:
- mailaddress.yaml

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
